### ISSUE TITLE
how to use output

### ISSUE THREAD

**Issue by frank3427** [VSChina/compose-to-manifest#1]
can anyone provide instruction on how to use the output, I am new to azure?

**Comment by lijunchen** [comment]
Hi, you need to learn how to use [Azure IoT Edge](https://docs.microsoft.com/en-us/azure/iot-edge/) first. This is just a tool to help you convert Docker Compose project to Azure IoT Edge solution.

**Comment by frank3427** [comment]
thank you, that was what I needed
