### ISSUE TITLE
manifest erros

### ISSUE THREAD

**Issue by frank3427** [VSChina/compose-to-manifest#2]
I have a docker-compose files that I converted and then applied the manifest to hub. none of the modules will deploy.
 here is the error on one of the modules, they all are getting the same error.
<6> 2019-09-23 14:55:33.627 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module bluetooth1]\n  [Start module bluetooth1]\n)"
<6> 2019-09-23 14:55:33.627 +00:00 [INF] - Executing command: "Create module bluetooth1"
<3> 2019-09-23 14:55:33.694 +00:00 [ERR] - Executing command for operation ["create"] failed.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module bluetooth1: Request body is malformed
	caused by: invalid type: integer `2`, expected a string, StatusCode:400, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 123
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 96
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
<3> 2019-09-23 14:55:33.697 +00:00 [ERR] - Executing command for operation ["Command Group: (\n  [Create module bluetooth1]\n  [Start module bluetooth1]\n)"] failed.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module bluetooth1: Request body is malformed
	caused by: invalid type: integer `2`, expected a string, StatusCode:400, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 123
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 96
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
<3> 2019-09-23 14:55:33.700 +00:00 [ERR] - Step failed in deployment 11, continuing execution. Failure when running command Command Group: (
  [Create module bluetooth1]
  [Start module bluetooth1]
). Will retry in 00s.

I have attached the docker-compose and the deployment template

[deployment.template.txt](https://github.com/VSChina/compose-to-manifest/files/3642772/deployment.template.txt)
[docker-compose.txt](https://github.com/VSChina/compose-to-manifest/files/3642773/docker-compose.txt)

**Comment by lijunchen** [comment]
I'm not sure what happened... But you can check
1. Have you ever set docker registry credential in .env file?
2. If you specify network in your docker compose file, you should create network in your edge device  manually.

**Comment by frank3427** [comment]
> I'm not sure what happened... But you can check
> 
> 1. Have you ever set docker registry credential in .env file?
can you provide and example?
> 2. If you specify network in your docker compose file, you should create network in your edge device  manually.
yes, I created the network manually on the device
I can docker login manually from device
I had set the docker registry credentials in the azure portal

**Comment by lijunchen** [comment]
Try this to generate a more readable configuration
```
iotedge-compose -t project -i docker-compose.yml -o project-edge
# There are some warnings, because compose doesn't support deploy keyword
```

Open folder `project-edge` with VS Code, and install `Azure IoT Edge` extension.  

You can set registry credentials in `deployment.template.json` and `.env`. See more on [Add your registry credentials](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-python-module#add-your-registry-credentials).

Also notice that when you use volume such as `HOST:CONTAINER` I remember that if `HOST` is a volume name edge runtime will create this volume automatically if it doesn't exist. If `HOST` is a path, make sure this path exists in your edge device but not your development machine.

When you feel ok, in the VS Code explorer, right-click the `deployment.template.json` file and select `Generate IoT Edge Deployment Manifest` and then [deploy modules to device](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-python-module#deploy-modules-to-device).

**Comment by frank3427** [comment]
I did as you suggested and I am still seeing the same errors for all the modules;

---> (Inner Exception #7) Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module mqtt1: Request body is malformed
	caused by: invalid type: integer `2`, expected a string, StatusCode:400, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 123
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 96
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 83<---

here is the module section of the manifest;
`          "mqtt1": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "started489361id/test-only:mqtt64arm_v1.3",
              "createOptions": "{\"ExposedPorts\":{\"11883/tcp\":{}},\"HostConfig\":{\"NetworkMode\":\"dnet201805090000.999\",\"RestartPolicy\":{\"Name\":\"always\",\"MaximumRetryCount\":0},\"PortBindings\":{\"11883/tcp\":[{\"HostIp\":\"\",\"HostPort\":\"11883\"}]},\"LogConfig\":{\"Type\":\"json-file\",\"Config\":{\"max-file\":\"3\",\"max-size\":\"2m\"}}},\"NetworkingConfig\":{\"EndpointsConfig\":{\"dnet201805090000.999\":{\"Aliases\":[\"mqtt1\"],\"IPAMConfig\":{}}}},\"Labels\":{\"com.docker.compose.project\":\"files\",\"com.docker.compose.service\":\"mqtt1\",\"com.docker.compose.oneoff\":\"False\",\"com.docke",
              "createOptions01": "r.compose.container-number\":\"1\",\"com.docker.compose.version\":\"1.24.0\",\"com.docker.compose.config-hash\":\"cd658336b1e5727f64b265cb2dba0c6b862c9ff1d4ac413f7b4f754c7119ddd5\"}}"
            }
          },`

**Comment by lijunchen** [comment]
> caused by: invalid type: integer 2, expected a string, StatusCode:400, at: at

I have no idea about this error message. But after delete `RestartPolicy` in `HostConfig` module starts normally. 

```python
"mqtt1": {
  ...,
  "restartPolicy": "always",
  "settings": {
    ...,
    "createOptions": {
      "HostConfig": {
        "RestartPolicy": {    # <- I forgot to delete this
          "Name": "always",
          "MaximumRetryCount": 0
        },
      }
    }
  }
}
```

This bug has been fixed. You can clone this repo to get latest version and use `convertor.py` directly
```bash
python3 convertor/convertor.py [-h] -t [file|project] -i docker_compose_file_path -o output_path [-r your_docker_container_registry_address]
```

I only use module `mqtt1` and set image as `redis:alpine` for test. This deployment.template.json file works for me.

```json
{
  "$schema-template": "2.0.0",
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": "",
            "registryCredentials": {
              "REGISTRY0": {
                "username": "$CONTAINER_REGISTRY_USERNAME",
                "password": "$CONTAINER_REGISTRY_PASSWORD",
                "address": "$CONTAINER_REGISTRY_ADDRESS"
              }
            }
          }
        },
        "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
              "createOptions": {}
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": {
                "HostConfig": {
                  "PortBindings": {
                    "5671/tcp": [
                      {
                        "HostPort": "5671"
                      }
                    ],
                    "8883/tcp": [
                      {
                        "HostPort": "8883"
                      }
                    ],
                    "443/tcp": [
                      {
                        "HostPort": "443"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "modules": {
          "mqtt1": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "redis:alpine",
              "createOptions": {
                "ExposedPorts": {
                  "11883/tcp": {}
                },
                "HostConfig": {
                  "NetworkMode": "dnet201805090000.999",
                  "PortBindings": {
                    "11883/tcp": [
                      {
                        "HostIp": "",
                        "HostPort": "11883"
                      }
                    ]
                  },
                  "LogConfig": {
                    "Type": "json-file",
                    "Config": {
                      "max-file": "3",
                      "max-size": "2m"
                    }
                  }
                },
                "NetworkingConfig": {
                  "EndpointsConfig": {
                    "dnet201805090000.999": {
                      "Aliases": [
                        "mqtt1"
                      ],
                      "IPAMConfig": {}
                    }
                  }
                },
                "Labels": {
                  "com.docker.compose.project": "proj",
                  "com.docker.compose.service": "mqtt1",
                  "com.docker.compose.oneoff": "False",
                  "com.docker.compose.container-number": "1",
                  "com.docker.compose.version": "1.24.0",
                  "com.docker.compose.config-hash": "543597488a6a48e12301ba6c2f9f71ae49aaae82f6b0beda41271acbc60ee8e5"
                }
              }
            }
          }
        }
      }
    },
    "$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "routes": {},
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    }
  }
}
```
Sorry for inconvenience and thanks for your feedback.

**Comment by formulahendry** [comment]
@frank3427 We have a fix on this. Please `pip install iotedge-compose==0.1.2` to have a try.
Let us know whether it is working now.

**Comment by frank3427** [comment]
yes working much better

**Comment by formulahendry** [comment]
@frank3427 Thank you! 
Closing this issue now,
