### ISSUE TITLE
Won't install due to obsolete pyyaml version

### ISSUE THREAD

**Issue by kohtala** [VSChina/compose-to-manifest#7]
The project won't install from pypi on Ubuntu 20.04.4 due to the old pyyaml version from 2018 does not compile. It is a dependency of the old docker-compose.

I tried cloning this project and upgrading docker-compose to latest release. It installs, but the output manifest is not correct.

docker-compose is soon out of maintenance. I think this project is also dead.

Would be polite to officially archive this project if it is abandoned.

**Comment by konichi3** [comment]
Thank you for the feedback. This repo is in maintenance mode (please see pinned thread).

**Comment by kohtala** [comment]
Thank you.
